/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.usuario;

/**
 *
 * @author dalto
 */
public class UsuarioView extends javax.swing.JPanel {

  /**
   * Creates new form usuarioView
   */
  public UsuarioView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel2 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    txtPesquisa = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableUsuario = new javax.swing.JTable();
    jLabel6 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    txtNome = new javax.swing.JTextField();
    txtEmail = new javax.swing.JTextField();
    txtEmail1 = new javax.swing.JTextField();
    txtEmail2 = new javax.swing.JTextField();
    jComboBox1 = new javax.swing.JComboBox();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setBackground(new java.awt.Color(255, 255, 255));

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jPanel5.setBackground(new java.awt.Color(255, 255, 255));
    jPanel5.setLayout(new java.awt.GridBagLayout());

    txtPesquisa.setBackground(java.awt.SystemColor.menu);
    txtPesquisa.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    txtPesquisa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txtPesquisa.setText("Pesquisa");
    txtPesquisa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.ipadx = 306;
    gridBagConstraints.ipady = 17;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(21, 132, 0, 0);
    jPanel5.add(txtPesquisa, gridBagConstraints);

    jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    jTableUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jTableUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
    jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jTableUsuario.setToolTipText("");
    jTableUsuario.setCellSelectionEnabled(true);
    jTableUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jTableUsuario.setFillsViewportHeight(true);
    jTableUsuario.setFocusCycleRoot(true);
    jTableUsuario.setFocusable(false);
    jTableUsuario.setGridColor(new java.awt.Color(204, 204, 204));
    jTableUsuario.setName(""); // NOI18N
    jTableUsuario.setRequestFocusEnabled(false);
    jTableUsuario.setRowHeight(30);
    jTableUsuario.setSelectionBackground(new java.awt.Color(204, 204, 204));
    jScrollPane1.setViewportView(jTableUsuario);
    jTableUsuario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 707;
    gridBagConstraints.ipady = 409;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(25, 10, 0, 10);
    jPanel5.add(jScrollPane1, gridBagConstraints);

    jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
    jLabel6.setText("Usuario");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 18;
    gridBagConstraints.ipady = 10;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
    jPanel5.add(jLabel6, gridBagConstraints);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
    );

    jPanel2.add(jPanel1);

    jPanel3.setBackground(new java.awt.Color(38, 86, 186));
    jPanel3.setLayout(new java.awt.GridBagLayout());

    jPanel4.setBackground(new java.awt.Color(38, 86, 186));

    txtNome.setBackground(new java.awt.Color(250, 250, 250));
    txtNome.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    txtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txtNome.setText("Username");
    txtNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    txtEmail.setBackground(new java.awt.Color(250, 250, 250));
    txtEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txtEmail.setText("Email");
    txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    txtEmail1.setBackground(new java.awt.Color(250, 250, 250));
    txtEmail1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    txtEmail1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txtEmail1.setText("Password");
    txtEmail1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    txtEmail2.setBackground(new java.awt.Color(250, 250, 250));
    txtEmail2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    txtEmail2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txtEmail2.setText("Telefone");
    txtEmail2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    jComboBox1.setBackground(java.awt.SystemColor.menu);
    jComboBox1.setEditable(true);
    jComboBox1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.setToolTipText("");
    jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jComboBox1.setFocusable(false);

    jLabel1.setBackground(new java.awt.Color(38, 86, 186));
    jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(250, 250, 250));
    jLabel1.setText("Role");

    jLabel2.setBackground(new java.awt.Color(38, 86, 186));
    jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(250, 250, 250));
    jLabel2.setText("Nome Completo");

    jLabel3.setBackground(new java.awt.Color(38, 86, 186));
    jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(250, 250, 250));
    jLabel3.setText("Email");

    jLabel4.setBackground(new java.awt.Color(38, 86, 186));
    jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(250, 250, 250));
    jLabel4.setText("Passwoard");

    jLabel5.setBackground(new java.awt.Color(38, 86, 186));
    jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(250, 250, 250));
    jLabel5.setText("Contacto");

    jButton1.setBackground(new java.awt.Color(0, 204, 102));
    jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setText("Salvar");
    jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jButton1.setContentAreaFilled(false);
    jButton1.setFocusPainted(false);
    jButton1.setOpaque(true);

    jButton2.setBackground(new java.awt.Color(255, 0, 51));
    jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("Cancelar");
    jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jButton2.setContentAreaFilled(false);
    jButton2.setFocusPainted(false);
    jButton2.setOpaque(true);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel4)
          .addComponent(jLabel3)
          .addComponent(jLabel2)
          .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(txtEmail)
            .addComponent(txtNome)
            .addComponent(txtEmail1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                  .addComponent(jComboBox1, 0, 1, Short.MAX_VALUE)
                  .addGap(18, 18, 18))
                .addGroup(jPanel4Layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addGap(130, 130, 130)))
              .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5)
                .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
              .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(55, 55, 55)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(60, 60, 60)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(51, Short.MAX_VALUE))
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipady = 40;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(61, 10, 11, 10);
    jPanel3.add(jPanel4, gridBagConstraints);

    jPanel2.add(jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableUsuario;
  private javax.swing.JTextField txtEmail;
  private javax.swing.JTextField txtEmail1;
  private javax.swing.JTextField txtEmail2;
  private javax.swing.JTextField txtNome;
  private javax.swing.JTextField txtPesquisa;
  // End of variables declaration//GEN-END:variables
}
